set={10,20,30,55,70,78}
set.add(75)
print(set)
set.pop()
print(set)
set.remove(30)
print(set)
set.copy()
print(set)
set.discard(78)
print(set)
set.clear()
print(set)

a = {2,3,4,5}
b={1,2,3,4}
c=a.union(b)
print(c)
c1 = a.intersection(b)
print(c1)
c7=a.intersection_update(b)
print(c7)
c2 = a.difference(b)
print(c2)
c6=a.difference_update(b)
print(c6)
c3 = a.issubset(b)
print(c3)
c4 = a.issuperset(b)
print(c4)
c5 = a.isdisjoint(b)
print(c5)
